import fs from 'fs'
import path from 'path'

// Pending change-proposals generated by unattended (overnight) caretaking that are
// NOT auto-applied — they wait for the user's morning review. Stored as JSON files
// in data/pending/ (gitignored, per-machine), one per proposal. Each holds the same
// { changes, log_entry, summary } contract the review UI already understands, so the
// morning surface just feeds it to <ProposalReview/>.

const PENDING_DIR = path.join(process.cwd(), 'data', 'pending')

export type PendingProposal = {
  id: string
  createdAt: string
  origin: string // what produced it, e.g. "nightly-curation"
  summary: string
  log_entry: string
  changes: unknown[]
}

function ensureDir() {
  fs.mkdirSync(PENDING_DIR, { recursive: true })
}

export function savePending(p: Omit<PendingProposal, 'id' | 'createdAt'>): PendingProposal {
  ensureDir()
  const id = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
  const full: PendingProposal = { id, createdAt: new Date().toISOString(), ...p }
  fs.writeFileSync(path.join(PENDING_DIR, `${id}.json`), JSON.stringify(full, null, 2), 'utf-8')
  return full
}

export function listPending(): PendingProposal[] {
  ensureDir()
  return fs.readdirSync(PENDING_DIR)
    .filter(f => f.endsWith('.json'))
    .map(f => {
      try { return JSON.parse(fs.readFileSync(path.join(PENDING_DIR, f), 'utf-8')) as PendingProposal }
      catch { return null }
    })
    .filter((p): p is PendingProposal => !!p)
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt))
}

export function getPending(id: string): PendingProposal | null {
  try {
    return JSON.parse(fs.readFileSync(path.join(PENDING_DIR, `${safeId(id)}.json`), 'utf-8')) as PendingProposal
  } catch {
    return null
  }
}

export function removePending(id: string): void {
  try { fs.rmSync(path.join(PENDING_DIR, `${safeId(id)}.json`)) } catch { /* already gone */ }
}

export function countPending(): number {
  ensureDir()
  return fs.readdirSync(PENDING_DIR).filter(f => f.endsWith('.json')).length
}

// Ids are app-generated, but never trust a path segment from a request.
function safeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9_-]/g, '')
}
